spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 5218791
    url: jdbc:mysql://127.0.0.1/cell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true